### ISSUE TITLE
AD936X_LIBIIO DEVICE AND FMCOMMS2 BOARD

### ISSUE THREAD

**Issue by KAUSHAL1986** [rodrigo455/AD936X_LIBIIO#1]
Hi

This is with reference to "https://stackoverflow.com/questions/52490594/fmcomms2-frontend-interface-redhawk-sdr-device".

With your reply i compiled ad936x_libiio tag 2.0 and was able to configure fmcommm2 board with redhawk 2.0.8 version successfully.

Now I have written FM TX component to send FM data to "dataShortTX_in" port of the ad936x_libiio device in a waveform application using the "usesdevice" property.

I am able to deploy the waveform without any problem but the inteded data from FM TX component is not reaching the ad936x_libiio device input.

Please point to anything I am doing wrong so I can proceed.
I am attaching test.tar.gz file which contains the following for your reference:
KKfmtx.cpp and KKfmtx.h for the FM TX component.

Screenshot from 2018-11-05 11-02-22.png contains the screenshot of the diagram of waveform being tested.

audio_test.sad.xml is the SAD file of the waveform being deployed.

All other files of the FM TX component are unchanged which I have not attached to avoid unnecessary details.

[test.tar.gz](https://github.com/rodrigo455/AD936X_LIBIIO/files/2547070/test.tar.gz)

KK

**Comment by rodrigo455** [comment]
I'll take a look at your files later... but I think that the issue lies in your sad file. bear in mind that the connection ID that connects dataShortTX_in must have the same value of the tx tuner allocation id.

edit:
as I suspected... your usesdevice relationship is missing the allocation properties for the TX tuner. 
please check [this link](https://stackoverflow.com/questions/22329993/usrp-uhd-source-and-sink-for-redhawk?noredirect=1&lq=1) .

**Comment by KAUSHAL1986** [comment]
thanks a lot for the pointers it is working now sorry for the late reply
